spring:
  datasource:
    url: jdbc:h2:mem:librarybase
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console.enabled: true

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    enabled: true
    filter: true

scheduler:
  lendingTerm:
    daysBeforeLendingTermExpiry: 0
    cron: "*/5 * * * * ?"
#    "0 0/1 ** * ?"
#  "0 0 0 ** ?"
#  "0 0/1 ** * ?"